# Generated by Django 5.0.1 on 2024-02-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('fr', 'Frais'), ('cs', 'Conserve'), ('em', 'Emballé')], default='em', max_length=2),
        ),
    ]
