# Generated by Django 5.0.1 on 2024-05-12 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_alter_commande_datecde_alter_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date(2024, 5, 12), null=True),
        ),
    ]
